/**
 * Blog Form Controller
 * Handles both create and edit modes for blog posts.
 * Depends on: config.js, utils.js, auth.js, api.js
 */

(function () {
    'use strict';

    // Require authentication
    if (!Auth.requireAuth()) return;

    // ============================================
    // Determine Mode
    // ============================================
    const isEditMode = window.location.pathname.includes('blog-edit');
    const blogId = isEditMode ? Utils.getQueryParam('id') : null;

    // ============================================
    // DOM Elements
    // ============================================
    const loadingScreen = document.getElementById('loading-screen');
    const errorScreen = document.getElementById('error-screen');
    const errorText = document.getElementById('error-text');
    const mainContent = document.getElementById('main-content');
    const form = document.getElementById('blog-form');
    const errorAlert = document.getElementById('error-alert');
    const submitBtn = document.getElementById('submit-btn');

    // Form fields
    const titleInput = document.getElementById('title');
    const slugInput = document.getElementById('slug');
    const categoryInput = document.getElementById('category');
    const excerptInput = document.getElementById('excerpt');
    const tagsInput = document.getElementById('tags');
    const contentInput = document.getElementById('content');
    const featuredImageInput = document.getElementById('featured_image_url');
    const authorNameInput = document.getElementById('author_name');
    const authorAvatarInput = document.getElementById('author_avatar_url');
    const authorBioInput = document.getElementById('author_bio');
    const authorTwitterInput = document.getElementById('author_twitter');
    const authorLinkedinInput = document.getElementById('author_linkedin');
    const authorGithubInput = document.getElementById('author_github');
    const authorWebsiteInput = document.getElementById('author_website');
    const ctaTextInput = document.getElementById('cta_text');
    const ctaUrlInput = document.getElementById('cta_url');
    const ctaStyleInput = document.getElementById('cta_style');
    const ctaPositionInput = document.getElementById('cta_position');
    const publishedInput = document.getElementById('published');
    const isFeaturedInput = document.getElementById('is_featured');

    // ============================================
    // Initialization
    // ============================================
    async function init() {
        bindEvents();

        if (isEditMode) {
            if (!blogId) {
                showError('No blog ID provided');
                return;
            }
            await loadBlog();
        } else {
            // New mode - show form immediately
            if (mainContent) {
                mainContent.classList.remove('hidden');
            }
        }
    }

    function bindEvents() {
        // Auto-generate slug from title
        titleInput.addEventListener('input', Utils.debounce(() => {
            if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                slugInput.value = Utils.slugify(titleInput.value);
                slugInput.dataset.autoGenerated = 'true';
            }
        }, 300));

        // Mark slug as manually edited if user changes it
        slugInput.addEventListener('input', () => {
            slugInput.dataset.autoGenerated = 'false';
        });

        // Form submission
        form.addEventListener('submit', handleSubmit);
    }

    // ============================================
    // Load Blog (Edit Mode)
    // ============================================
    async function loadBlog() {
        try {
            const blog = await BlogsApi.getById(parseInt(blogId, 10));
            populateForm(blog);
            showContent();
        } catch (error) {
            console.error('Failed to load blog:', error);
            showError(error.message || 'Failed to load blog');
        }
    }

    function populateForm(blog) {
        titleInput.value = blog.title || '';
        slugInput.value = blog.slug || '';
        categoryInput.value = blog.category || '';
        excerptInput.value = blog.excerpt || '';
        tagsInput.value = (blog.tags || []).join(', ');
        contentInput.value = blog.content || '';
        featuredImageInput.value = blog.featured_image_url || '';
        authorNameInput.value = blog.author_name || '';
        authorAvatarInput.value = blog.author_avatar_url || '';
        authorBioInput.value = blog.author_bio || '';
        authorTwitterInput.value = blog.author_twitter || '';
        authorLinkedinInput.value = blog.author_linkedin || '';
        authorGithubInput.value = blog.author_github || '';
        authorWebsiteInput.value = blog.author_website || '';
        ctaTextInput.value = blog.cta_text || '';
        ctaUrlInput.value = blog.cta_url || '';
        ctaStyleInput.value = blog.cta_style || 'primary';
        ctaPositionInput.value = blog.cta_position || 'bottom';
        publishedInput.checked = !!blog.published;
        isFeaturedInput.checked = !!blog.is_featured;
    }

    // ============================================
    // UI State Management
    // ============================================
    function showContent() {
        if (loadingScreen) loadingScreen.classList.add('hidden');
        if (errorScreen) errorScreen.classList.add('hidden');
        if (mainContent) mainContent.classList.remove('hidden');
    }

    function showError(message) {
        if (loadingScreen) loadingScreen.classList.add('hidden');
        if (mainContent) mainContent.classList.add('hidden');
        if (errorScreen) {
            errorScreen.classList.remove('hidden');
            if (errorText) errorText.textContent = message;
        }
    }

    function showFormError(message) {
        errorAlert.textContent = message;
        errorAlert.classList.remove('hidden');
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    function hideFormError() {
        errorAlert.classList.add('hidden');
    }

    function setSubmitting(submitting) {
        submitBtn.disabled = submitting;

        if (submitting) {
            submitBtn.innerHTML = `
        <div class="spinner" style="width: 20px; height: 20px; border-width: 2px;"></div>
        <span>${isEditMode ? 'Updating...' : 'Creating...'}</span>
      `;
        } else {
            submitBtn.innerHTML = `
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/>
          <polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/>
        </svg>
        <span>${isEditMode ? 'Update Blog Post' : 'Create Blog Post'}</span>
      `;
        }
    }

    // ============================================
    // Form Submission
    // ============================================
    async function handleSubmit(e) {
        e.preventDefault();
        hideFormError();

        // Validate required fields
        const title = titleInput.value.trim();
        const content = contentInput.value.trim();

        if (!title) {
            showFormError('Title is required');
            titleInput.focus();
            return;
        }

        if (!content) {
            showFormError('Content is required');
            contentInput.focus();
            return;
        }

        // Build form data
        const formData = {
            title,
            slug: slugInput.value.trim() || Utils.slugify(title),
            excerpt: excerptInput.value.trim(),
            content,
            category: categoryInput.value.trim(),
            tags: tagsInput.value
                .split(',')
                .map(t => t.trim())
                .filter(t => t.length > 0),
            featured_image_url: featuredImageInput.value.trim(),
            author_name: authorNameInput.value.trim(),
            author_bio: authorBioInput.value.trim(),
            author_avatar_url: authorAvatarInput.value.trim(),
            author_twitter: authorTwitterInput.value.trim(),
            author_linkedin: authorLinkedinInput.value.trim(),
            author_facebook: '',
            author_instagram: '',
            author_github: authorGithubInput.value.trim(),
            author_website: authorWebsiteInput.value.trim(),
            cta_text: ctaTextInput.value.trim(),
            cta_url: ctaUrlInput.value.trim(),
            cta_style: ctaStyleInput.value,
            cta_position: ctaPositionInput.value,
            published: publishedInput.checked,
            is_featured: isFeaturedInput.checked
        };

        setSubmitting(true);

        try {
            if (isEditMode) {
                await BlogsApi.update(parseInt(blogId, 10), formData);
                Utils.showToast('Blog updated successfully', 'success');
            } else {
                await BlogsApi.create(formData);
                Utils.showToast('Blog created successfully', 'success');
            }

            // Redirect to dashboard after short delay for toast to show
            setTimeout(() => {
                window.location.href = CMS_CONFIG.ROUTES.DASHBOARD;
            }, 500);
        } catch (error) {
            console.error('Save failed:', error);
            showFormError(error.message || 'Failed to save blog');
            setSubmitting(false);
        }
    }

    // ============================================
    // Start
    // ============================================
    init();
})();
